### ISSUE TITLE
GetConfig.ps1 not prompting for UE4 Path

### ISSUE THREAD

**Issue by christopher-buss** [NansPellicari/UE4-TPL-CppWithTestEnv#1] opened 2020-06-09 23:33 UTC
When I ran the code and tried to rename the project file, all I get is a

> Wrong path " " given for the engine directory, can't find the "Engine\Build\BatchFiles\Build.bat" file.

There is never a prompt asking me to enter the UE4 path.

Unaware of the issue, not sure if the GetConfig file is being called correctly (tried adding a Write-Host to start of file but it never outputs to console).

**Comment by christopher-buss** [comment] 2020-06-09 23:47
Okay. After some more digging around, I realised it is due to my project location being in a file called "Unreal Projects". The space within these was disallowing the program to actually find the file.

Would it be possible to either add a note to ensure that the user does not have a space in their folder names, or even better, that file locations with a space in them are accepted by the bat files! 👯‍♂️

**Comment by NansPellicari** [comment] 2020-06-09 23:49
Hi @christopher-buss,
Thanks for your feedback, to quickly fix the issue you can add this line in the `Config/Project.ini`
```
UE4PATH=c:\MyPath\To\UE4\Directory
```
To help me finding a better solution and reproduce the issue, did you launch the script `ChangeProjectName.bat` with the `-f` options ?

**Comment by NansPellicari** [comment] 2020-06-10 00:07
> Okay. After some more digging around, I realised it is due to my project location being in a file called "Unreal Projects". The space within these was disallowing the program to actually find the file.
> 
> Would it be possible to either add a note to ensure that the user does not have a space in their folder names, or even better, that file locations with a space in them are accepted by the bat files! 👯‍♂️

Ok i'm glad you found the fix! Yes you right and it should be better to make the bat accepts spaces in the path. It's late here, I make the fix tomorrow and close the issue when it's done.

**Comment by NansPellicari** [comment] 2020-06-10 12:14
Hi @christopher-buss,

I've found a fix here #2 , there was 2 issues actually:
1. The first was due to the way the bat calls `Scripts/GetConfig.ps1`. In the actual state it can't prompt to user and waiting for user's input... I changed it regarding this post: https://blog.danskingdom.com/allow-others-to-run-your-powershell-scripts-from-a-batch-file-they-will-love-you-for-it/
2. The second it's about spaces in project path as you said, but it occures in different location:
    * in the bat `GenerateProjectFiles.bat`
    * in the OpenCppCoverage args in `RunTest.bat`

I'll really appreciate if you can give a try to the fix from this branch  [fix/issue-1](https://github.com/NansPellicari/UE4-TPL-CppWithTestEnv/tree/fix/issue-1) and let me know if it's working for you before I merge the PR.

ps: don't forget to use the correct branch when you are located in the cloned dir:
```
git checkout fix/issue-1
```

**Comment by christopher-buss** [comment] 2020-06-10 19:39
I have checked out the branch, and loaded the file into a new folder called "Unreal Projects" with the space. I got the prompt to ask for my unreal path! As far as I can see, there is no issues present. I have found another issue though, but I will open a separate pull request for this one.

**Comment by NansPellicari** [comment] 2020-06-10 21:34
> I have checked out the branch, and loaded the file into a new folder called "Unreal Projects" with the space. I got the prompt to ask for my unreal path! As far as I can see, there is no issues present. I have found another issue though, but I will open a separate pull request for this one.

OK nice, i look into the second issue, i close this one! Thanks a lot ;-)

**Closed as completed** 2020-06-10 22:05 UTC
